### ISSUE TITLE
GitHub Ribbon on Core.js's website

### ISSUE THREAD

**Issue by quangv** [OscarGodson/Core.js#9]
Hello, it took me way to long to get to this github repository from it's webpage http://oscargodson.github.com/Core.js/

suggest having a ribbon on top-right corner or/and github badges etc. :)

**Comment by OscarGodson** [comment]
Good idea. At the bottom of the page theres a link and you can also just do: http://github.com/<username>/<projectname> in the future for other repos.

This isn't really maintained all that much tho these days. If this shows my interest in the community i might come back to it tho :)

**Comment by OscarGodson** [comment]
OK, ribbon added! http://oscargodson.github.com/Core.js/

**Comment by quangv** [comment]
nice... yeh it took me almost 1 minute to find, way too long ;)
